DiningManagementSystem/Areas/Security/Controllers/ChangeStudentPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using BLL;

namespace DiningManagementSystem.Areas.Security.Controllers
{
    public class ChangeStudentPasswordController : Controller
    {
        private StudentManager studentManager;

        public ChangeStudentPasswordController()
        {
            studentManager=new StudentManager();
        }
        //
        // GET: /Security/ChangeStudentPassword/
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(BOL.Student student)
        {
            var students = studentManager.GetAllStudents().Where(x => x.Email == User.Identity.Name).FirstOrDefault();

            if (student.Password == null )
            {
                TempData["Msgp"] = "This Value is Required";
                return RedirectToAction("Index");

            }
            else if (student.NewPassword == null )
            {
                TempData["Msgn"] = "This Value is Required";
                return RedirectToAction("Index");
            }
            else if (student.NewConfrimPassword == null)
            {
                TempData["Msgc"] = "This Value is Required";
                return RedirectToAction("Index");
            }
            else
            {


                if (student.NewPassword == student.NewConfrimPassword)
                {

                    if (Crypto.VerifyHashedPassword(students.Password, student.Password))
                    {
                        students.Password = Crypto.HashPassword(student.NewPassword);
                        students.NewPassword = Crypto.HashPassword(student.NewPassword);
                        students.ConfrimPassword = Crypto.HashPassword(student.NewPassword);
                        studentManager.Update(students);
                        TempData["Msg"] = "Password Successfully Changed";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Msg"] = "Password Changed unsuccessfull";
                        return RedirectToAction("Index");
                    }
                }

                else
                {
                    TempData["Msg1"] = "New Password & new Confirm password didn't mached";
                    return RedirectToAction("Index");

                }
            }

        }
	}
}

DiningManagementSystem/Areas/Security/Views/ChangeStudentPassword/Index.cshtml
@model BOL.Student

@{
    ViewBag.Title = "Change Password";
}
<br />
<br />
<br/>
<h5>Change Password here</h5>

@using (Html.BeginForm("ChangePassword","ChangeStudentPassword",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true)

@if (TempData["Msg"] != null)
{
    <div class="alert alert-dismissible alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @TempData["Msg"]
    </div>
}

        <div class="form-group">
            <div class="control-label col-md-2"><b>Old Password</b></div>
            <div class="col-md-4">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Password)
                @TempData["Msgp"]
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NewPassword)
                @TempData["Msgn"]
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NewConfrimPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.PasswordFor(model => model.NewConfrimPassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NewConfrimPassword)
                @TempData["Msg1"]
                @TempData["Msgc"]
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}