DiningManagementSystem/Areas/Student/Controllers/ExpenseDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;

namespace DiningManagementSystem.Areas.Student.Controllers
{
    [Authorize(Roles = "U")]
    public class ExpenseDetailsController : Controller
    {
        private MealManager mealManager;
        private ExpenseManager expenseManager;
        private StudentManager studentManager;
        private PaymentManager paymentManager;

        public ExpenseDetailsController()
        {
            mealManager=new MealManager();
            expenseManager=new ExpenseManager();
            studentManager=new StudentManager();
            paymentManager=new PaymentManager();
        }
        //
        // GET: /Student/ExpenseDetails/
        public ActionResult Index()
        {

            ViewBag.Month = TempData["Month"];
            return View();
        }

        public ActionResult Create(int month)
        {



            TempData["Month"] = month.ToString();
            


            var student = studentManager.GetAllStudents().Where(x => x.Email == User.Identity.Name);
            int studentId = student.FirstOrDefault().StudentId;
            TempData["studentId"] = studentId;


            int studentTotalMeal = studentManager.StudentTotalMeal(studentId, month);

            TempData["studentTotalMeal"] = studentTotalMeal;


            decimal studentPayment = paymentManager.TotalPayment(studentId, month);
            TempData["studentPayment"] = System.Math.Round(studentPayment, 3);

            if (studentTotalMeal == 0 && studentPayment == 0)
            {
                TempData["Msg"] = "Opps!! Sorry you haven't take  meal in this month";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Msg1"] = "1";
            }


            decimal mealRate = 0;
            if (mealManager.TotalMeal(month) != 0)
            {
                mealRate = expenseManager.TotalExpense(month) / mealManager.TotalMeal(month);
            }
            TempData["MealRate"] = System.Math.Round(mealRate, 3);

           

            decimal studentExpense = mealRate * studentTotalMeal;
            TempData["studentExpense"] = System.Math.Round(studentExpense, 3);


            if (studentPayment < studentExpense)
            {
                TempData["haveToPay"] = System.Math.Round(studentExpense - studentPayment, 3);
            }
            if (studentPayment > studentExpense)
            {
                TempData["Receive"] = System.Math.Round(studentPayment - studentExpense, 3);
            }

            return RedirectToAction("Index");
        }
    }
}

DiningManagementSystem/Areas/Student/Views/ExpenseDetails/Index.cshtml
@model BOL.Meal

@{
    ViewBag.Title = "Expense Details";
}
<br />
<br />
<br/>
<h5>Your Meal Expense Details</h5>

@if (TempData["Msg"] != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @TempData["Msg"]
    </div>
}


@using (Html.BeginForm("Create", "ExpenseDetails", FormMethod.Post))
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-2">
                <b>Select Month &nbsp;&nbsp;   </b>
            </div>
            <div class="col-md-4">
                <select id="month" name="month" class="form-control" onchange="this.form.submit()">
                  
                    @if (ViewBag.Month == null)
                    {
                        <option value="0" selected="">Select Month</option>
                    }
                    else
                    {
                        <option value="0" >Select Month</option>
                    }
                    
                    @if (ViewBag.Month == "1")
                    {
                        <option value="1" selected="">January</option>
                    }
                    else
                    {
                        <option value="1">January</option>
                    }
                    @if (ViewBag.Month == "2")
                    {
                        <option value="2" selected="">February</option>
                    }
                    else
                    {
                        <option value="2">February</option>
                    }
                   @if (ViewBag.Month == "3")
                    {
                        <option value="3" selected="">March</option>
                    }
                    else
                    {
                       <option value="3">March</option>
                    }
                    @if (ViewBag.Month == "4")
                    {
                        <option value="4" selected="">April</option>
                    }
                    else
                    {
                        <option value="4">April</option>
                    }
                    @if (ViewBag.Month == "5")
                    {
                        <option value="5" selected="">May</option>
                    }
                    else
                    {
                        <option value="5">May</option>
                    }
                    @if (ViewBag.Month == "6")
                    {
                        <option value="6" selected="">June</option>
                    }
                    else
                    {
                        <option value="6">June</option>
                    }
                    @if (ViewBag.Month == "7")
                    {
                        <option value="7" selected="">July</option>
                    }
                    else
                    {
                        <option value="7">July</option>
                    }

                    @if (ViewBag.Month == "8")
                    {
                        <option value="8" selected="">August</option>
                    }
                    else
                    {
                        <option value="8">August</option>
                    }
                    @if (ViewBag.Month == "9")
                    {
                        <option value="9" selected="">September</option>
                    }
                    else
                    {
                        <option value="9">September</option>
                    }
                    @if (ViewBag.Month == "10")
                    {
                        <option value="10" selected="">October</option>
                    }
                    else
                    {
                        <option value="10">October</option>
                    }
                    @if (ViewBag.Month == "11")
                    {
                        <option value="11" selected="">November</option>
                    }
                    else
                    {
                        <option value="11">November</option>
                    }
                    @if (ViewBag.Month == "12")
                    {
                        <option value="12" selected="">December</option>
                    }
                    else
                    {
                        <option value="12">December</option>
                    }
                    
                </select>
            </div>
        </div>




    </div>
   
}
@if (TempData["Msg1"] == "1")
{
    <table class="table table-striped table-bordered table-hover">
        <tr style="background: #a9a9a9; color: white">
            <td>Todays Date</td>
            <td>@DateTime.Now.ToLongDateString()</td>
        </tr>
        <tr>
            <td>Your Meal Id</td>
            <td>@TempData["studentId"]</td>
        </tr>
        <tr>
            <td>Your Total Meal Number</td>
            <td>@TempData["studentTotalMeal"]</td>
        </tr>
        <tr>
            <td>Earlier You Payed</td>
            <td>@TempData["studentPayment"] BDT</td>
        </tr>
        <tr>
            <td>Meal Rate</td>
            <td>@TempData["MealRate"] BDT</td>
        </tr>

        <tr>
            <td>Your Expense</td>
            <td>@TempData["studentExpense"] BDT</td>
        </tr>


        @if (TempData["haveToPay"] != null)
        {
            <tr>
                <td>You have to Pay</td>
                <td>@TempData["haveToPay"] BDT</td>
            </tr>
        }
        @if (TempData["Receive"] != null)
        {
            <tr>
                <td>You will Receive</td>
                <td>@TempData["Receive"] BDT</td>
            </tr>
        }



    </table>
}





        